//===----------------------------------------------------------------------===//
//
// Copyright 2020-2021 The ScaleHLS Authors.
//
//===----------------------------------------------------------------------===//

#ifndef BINDINGS_PYTHON_HLSCPP_OPS_TD
#define BINDINGS_PYTHON_HLSCPP_OPS_TD

include "mlir/Bindings/Python/Attributes.td"
include "scalehls/Dialect/HLSCpp/HLSCpp.td"

#endif // BINDINGS_PYTHON_HLSCPP_OPS_TD
