//===----------------------------------------------------------------------===//
//
// Copyright 2020-2021 The ScaleHLS Authors.
//
//===----------------------------------------------------------------------===//

#ifndef BINDINGS_PYTHON_HLS_OPS_TD
#define BINDINGS_PYTHON_HLS_OPS_TD

include "mlir/Bindings/Python/Attributes.td"
include "scalehls/Dialect/HLS/HLSOps.td"

#endif // BINDINGS_PYTHON_HLS_OPS_TD
