//===----------------------------------------------------------------------===//
//
// Copyright 2020-2021 The ScaleHLS Authors.
//
//===----------------------------------------------------------------------===//

#ifndef PYTHON_SCALEHLS_DIALECTS_HLSOPS_TD
#define PYTHON_SCALEHLS_DIALECTS_HLSOPS_TD

include "mlir/Bindings/Python/Attributes.td"
include "scalehls/Dialect/HLS/IR/HLSOps.td"

#endif // PYTHON_SCALEHLS_DIALECTS_HLSOPS_TD
