from typing import ClassVar

class MemoryKind:
    __members__: ClassVar[dict] = ...  # read-only
    BRAM_1P: ClassVar[MemoryKind] = ...
    BRAM_2P: ClassVar[MemoryKind] = ...
    BRAM_S2P: ClassVar[MemoryKind] = ...
    BRAM_T2P: ClassVar[MemoryKind] = ...
    DRAM: ClassVar[MemoryKind] = ...
    LUTRAM_1P: ClassVar[MemoryKind] = ...
    LUTRAM_2P: ClassVar[MemoryKind] = ...
    LUTRAM_S2P: ClassVar[MemoryKind] = ...
    UNKNOWN: ClassVar[MemoryKind] = ...
    URAM_1P: ClassVar[MemoryKind] = ...
    URAM_2P: ClassVar[MemoryKind] = ...
    URAM_S2P: ClassVar[MemoryKind] = ...
    URAM_T2P: ClassVar[MemoryKind] = ...
    __entries: ClassVar[dict] = ...
    def __init__(self, value: int) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: object) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

def get_live_ins(task_op: MlirOperation) -> list: ...
def get_parent_task(op: MlirOperation) -> MlirOperation: ...
