from typing import Callable


def add_comprehensive_bufferize_passes(
    pass_manager: MlirPassManager) -> None: ...
def add_convert_dataflow_to_func_passes(
    pass_manager: MlirPassManager) -> None: ...


def add_create_dataflow_passes(pass_manager: MlirPassManager) -> None: ...
def add_linalg_transform_passes(pass_manager: MlirPassManager) -> None: ...
def add_lower_dataflow_passes(pass_manager: MlirPassManager) -> None: ...
def emit_hlscpp(module: MlirModule, file_object: object) -> bool: ...
def get_static_loop_ranges(linalg_op: MlirOperation) -> list: ...
def register_everything(context: object) -> None: ...


def walk_operation(self: MlirOperation, callback: Callable[[
                   MlirOperation], None]) -> None: ...
