//===----------------------------------------------------------------------===//
//
// Copyright 2020-2021 The ScaleHLS Authors.
//
//===----------------------------------------------------------------------===//

#ifndef PYTHON_SCALEHLS_DIALECTS_HLSTRANSFORMOPS_TD
#define PYTHON_SCALEHLS_DIALECTS_HLSTRANSFORMOPS_TD

include "scalehls/Dialect/HLS/TransformOps/HLSTransformOps.td"

#endif // PYTHON_SCALEHLS_DIALECTS_HLSTRANSFORMOPS_TD
